---
- hosts: all
  become: yes
  become_method: sudo

  roles:
    - { role: 'ubuntu-base' }
    - { role: 'ubuntu-apache' }
    - { role: 'ubuntu-mysql' }
    - { role: 'ubuntu-php-7.1' }
    - { role: 'ubuntu-varnish' }
    - { role: 'ubuntu-nodejs-6.x' }
    - { role: 'ubuntu-probo' }
