---

- name: update apt
  apt: update_cache=yes

- name: install php dependencies
  apt: name={{ item }} state=present
  with_items:
    - 'php5'
    - 'php5-cli'
    - 'php5-common'
    - 'php5-curl'
    - 'php5-dev'
    - 'php5-gd'
    - 'php5-imagick'
    - 'php5-json'
    - 'php5-ldap'
    - 'php5-mcrypt'
    - 'php5-mysql'
    - 'php5-readline'
    - 'php5-redis'
    - 'php-soap'
    - 'php5-pgsql'
    - 'imagemagick'
    - 'libapache2-mod-php5'
    - 'php-pear'

- name: install redis
  apt:
    name: redis-server
    state: present

- name: install memcached
  apt:
    name: memcached
    state: present

- name: install libzip
  apt:
    name: libzip-dev
    state: present

- name: install php zip
  pear:
    name: pecl/zip
    state: present

- name: create php log dir
  file:
    path: /var/log/php
    state: directory
    mode: 0755
    owner: www-data
    group: root

- name: create PHP error log file
  file:
    path: /var/log/php/error.log
    owner: www-data
    group: root
    mode: 0644
    state: touch

- import_tasks: php-ini.yml
